services:
  ai-studio-proxy:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: ai-studio-proxy-container
    mem_limit: ${DOCKER_MEMORY_LIMIT:-0}
    memswap_limit: ${DOCKER_MEMSWAP_LIMIT:-0}
    ports:
      - "${HOST_FASTAPI_PORT:-2048}:${DEFAULT_FASTAPI_PORT:-2048}"
      - "${HOST_STREAM_PORT:-3120}:${STREAM_PORT:-3120}"
    volumes:
      # Kimlik doğrulama dosyalarını bağla (zorunlu)
      - ../auth_profiles:/app/auth_profiles
      # .env yapılandırma dosyasını bağla (önerilir)
      # docker/.env.docker dosyasını docker/.env olarak kopyalayıp gerekli düzenlemeleri yapın
      - ../docker/.env:/app/.env:ro
      # Log dizinini bağla (opsiyonel, logları kalıcı tutmak için)
      # Yetki hatası alırsanız sudo chmod -R 777 ../logs komutuyla izinleri güncelleyin
      # - ../logs:/app/logs
      # Özel sertifikaları bağla (opsiyonel)
      # - ../certs:/app/certs:ro
      # Script enjeksiyonu ile ilgili dosyaları bağla (opsiyonel; özel script/model yapılandırması için)
      # Özel Tampermonkey betikleriniz veya model yapılandırmalarınız varsa aşağıdaki satırları etkinleştirin
      # - ../browser_utils/custom_scripts:/app/browser_utils/custom_scripts:ro
      # - ../browser_utils/model_configs.json:/app/browser_utils/model_configs.json:ro
    environment:
      # Bu ortam değişkenleri .env dosyasındaki değerleri override eder
      # Yalnızca .env kullanmak istiyorsanız bu satırları yorum satırına alın
      - PYTHONUNBUFFERED=1
      # - PORT=${PORT:-8000}
      # - DEFAULT_FASTAPI_PORT=${DEFAULT_FASTAPI_PORT:-2048}
      # - DEFAULT_CAMOUFOX_PORT=${DEFAULT_CAMOUFOX_PORT:-9222}
      # - STREAM_PORT=${STREAM_PORT:-3120}
      # - SERVER_LOG_LEVEL=${SERVER_LOG_LEVEL:-INFO}
      # - DEBUG_LOGS_ENABLED=${DEBUG_LOGS_ENABLED:-false}
      # - AUTO_CONFIRM_LOGIN=${AUTO_CONFIRM_LOGIN:-true}
      # Proxy yapılandırması (opsiyonel)
      # - HTTP_PROXY=${HTTP_PROXY}
      # - HTTPS_PROXY=${HTTPS_PROXY}
      # - UNIFIED_PROXY_CONFIG=${UNIFIED_PROXY_CONFIG}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${DEFAULT_FASTAPI_PORT:-2048}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Opsiyonel: özel bir ağ ayarı gerekiyorsa
    # networks:
    #   - ai-studio-network

# Opsiyonel: özel ağ tanımı
# networks:
#   ai-studio-network:
#     driver: bridge
